version: '3.3'

services:
    database:
        image: postgres:alpine
        container_name: database
        restart: always
        ports:
            - "${DB_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: "${DB_USERNAME:-postgres}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
            POSTGRES_DB: "${DB_DATABASE:-postgres}"
        volumes:
            - ./storage/docker/postgres:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        ports:
            - "${REDIS_PORT:-6379}:6379"
        command: redis-server --save 60 1
        volumes:
            - ./storage/docker/redis:/data

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379:0,local:redis:6379:1
            - HTTP_USER=
            - HTTP_PASSWORD=
        ports:
            - 8081:8081
        depends_on:
            - redis

    frontend:
        image: node:18-alpine
        container_name: frontend
        restart: always
        ports:
            - "5173:5173"
        working_dir: /app
        command: npm run dev -- --host
        volumes:
            - ./:/app
